require:
  - rubocop-performance
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context' ]

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Metrics/AbcSize:
  Max: 30

Metrics/BlockNesting:
  Max: 4